### ISSUE TITLE
Vue.js + Apache Rewrite URL 이슈

### ISSUE THREAD

**Issue by endless87** [darkness87/AMIWeb#20]
Vue.js 와 Apache 사용시
새로고침 또는 root/url주소 로 입력시 404 에러를 출력 하는 이슈

**Comment by endless87** [comment]
Apache httpd 경로 : /etc/httpd/conf/httpd.conf

<VirtualHost *:8080> 안에

<Directory "/data/web_cass">                                                                                               
RewriteEngine on                                                                                                           
RewriteCond %{REQUEST_FILENAME} -f [OR]                                                                                    
RewriteCond %{REQUEST_FILENAME} -d                                                                                         
RewriteRule ^ - [L]                                                                                                        
RewriteRule ^ index.html [L]                                                                                               
</Directory>

위 내용 추가하여 적용하고 Apache 서비스 재기동

**Comment by darkness87** [comment]
내용 확인하였습니다.
