### ISSUE TITLE
메인 대시보드 - 맵데이터 정리

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#21]
맵 
 - 데이터 표기 되지 않음

**Comment by endless87** [comment]
검침현황과 장애현황에는 적용하였으나..
메인현황판에 적용하면 현재 0값으로 표기 되기 때문에 시연을 위한 임의데이터로 표기함
- 해당내용은 시연 완료 후 장애현황 맵 데이터와 동일하게 적용예정

**Comment by darkness87** [comment]
해당 기능은 운영서버 들어가서 확인될때까지 보관

**Comment by endless87** [comment]
API 적용

**Comment by darkness87** [comment]
![image](https://user-images.githubusercontent.com/20449373/119753078-1d149180-bed9-11eb-8864-c552a224d66e.png)
데이터가 상이하게 나옵니다. 확인해주세요

**Comment by endless87** [comment]
NaN으로 발생되는 데이터 0값으로 출력

API에서 초기 데이터 및 Flux API에 지도 정보 추가

데이터 주기 권장 1분
