### ISSUE TITLE
설비 - 장비관리 - 서치영역 미패핑 정보 가져오기 토글키 구현

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#25]
서치영역

미 매핑 정보 가져오기  
 -서치 영역에 2줄에 버튼으로 표시
 - dcu , meter 

![image](https://user-images.githubusercontent.com/78832275/117387473-ee337d00-af23-11eb-963a-240c03a91e44.png)
![image](https://user-images.githubusercontent.com/78832275/117387734-613cf380-af24-11eb-8cb8-73cfa028e546.png)

**Comment by darkness87** [comment]
토글 될 경우 검색바가 막혀야 합니다.
