### ISSUE TITLE
설비 - 장비관리 - DCU 매핑 정보 안나오던 문제

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#26]
dcu 매핑 정보 안나옴

**Comment by endless87** [comment]
DCU가 삭제 된 상태여서 나오던 이슈..
동관리 매핑된 관련 이슈 확인 필요
검색 창에 조회되는 DCU 정보 확인필요

**Comment by endless87** [comment]
#26 삭제 dcu 관련 처리

**Comment by darkness87** [comment]
현 이슈는 현시점에서 종료하고 추후 관리하는 방향으로 정리예정입니다.
