### ISSUE TITLE
검침 - 검침정보 - 수집정보

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#39]
검색 결과가 없음,

![image.png](https://images.zenhubusercontent.com/6052f3877bf33b1d79eb321b/50233acf-afc8-4d24-afeb-bd54a43b5fe6)

**Comment by darkness87** [comment]
서버에 데이터를 가져오지 못하던 일시적인 현상이며 현재는 정상동작하므로 종료합니다.
