### ISSUE TITLE
고객지원 - Q&A 데이터 삽입

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#51]
- 워드 문서 내용 넣기
- 그림 디자인 
- 하기 첨부문서를 통해 내용관리
[스마트그리드 확산사업 운영 안내.docx](https://github.com/darkness87/AMIWeb/files/6432750/default.docx)

**Comment by darkness87** [comment]
렉 현상 분석 확인이 필요합니다.

**Comment by darkness87** [comment]
렉 현상 분석 결과 wbox로 쌓여진 부분에 대한 이슈였으며 이를 걷어내고 퍼블리싱을 다시 해야할것으로 보입니다. 검토해주세요!
