### ISSUE TITLE
퍼블리싱 컴포넌트 추가해주세요

### ISSUE THREAD

**Issue by darkness87** [darkness87/AMIWeb#57]
개발과 퍼블리싱이 겹쳐져서 향후 유지보수 차원 관리가 불리해집니다.

이를 해결하기 위한 Vue용 퍼블리싱 가이드 파일이 필요합니다.

![image.png](https://images.zenhubusercontent.com/5d78977a59191331a1b51cd0/db335fc8-3cb5-44d5-951a-5fd3bde258bb)
상단의 표시된것과 같이 컴포넌트모음을 추가하여 관리해주시면됩니다.
파일 위치는 @pages/About.vue 입니다.

파일 작성 규칙은 Vue-Bootstrap 코드를 준수한 코드로 진행하면 수월할 것으로 보입니다.

```html
<template>
 <!-- 올바른 예  O -->
 <b-table />

 <!-- 올바르지 않은 예 X -->
 <table class="b-table" /> 

</template>
```

순수 html tag element를 지향하여 작성 부탁드립니다.

궁금하신 내역은 톡보단 댓글로 관리해요!!

**Comment by hongshinae** [comment]
Template 폴더 생성
 - Template01.vue  ( 기본 레이아웃 )
 - Template02.vue  ( 분할 화면 레이아웃 )
 - Template03.vue  ( 버튼, 테이블 기타 사용된 scss )
