### ISSUE TITLE
DCU 등록 화면 깨짐

### ISSUE THREAD

**Issue by endless87** [darkness87/AMIWeb#61]
![image.png](https://images.zenhubusercontent.com/5f27b089a9416e6cd5a2ba78/8f184f8b-6c31-4aaf-9906-bb778e1fd6f2)

DCU 등록 화면 깨짐

**Comment by darkness87** [comment]
해당 증상 재현되지 않습니다. 확인해주세요

**Comment by hongshinae** [comment]
scss 분리 중 발생 된 문제였습니다.  처리완료되었습니다.
