### ISSUE TITLE
공통 -  컴포넌트 모음 왼쪽 메뉴 넣기

### ISSUE THREAD

**Issue by hongshinae** [darkness87/AMIWeb#71]
공통 컴포넌트 왼쪽 메뉴설정에 넣기![image.png](https://images.zenhubusercontent.com/6052f3877bf33b1d79eb321b/8a3fffa1-930c-4582-822f-ac2f1ff1f4eb)

**Comment by hongshinae** [comment]
권한 설정 처리 부탁드립니다.

**Comment by endless87** [comment]
레벨 권한 값이 0 일경우에만 표기 해주세요.
- 해당내용은 임시로 일반 운영자와 사용가에게  화면에 노출하지 않기 위해 사용합니다.

**Comment by endless87** [comment]
로그인 시 response 권한 파라미터값

level : 0
