### ISSUE TITLE
검침-검침현황

### ISSUE THREAD

**Issue by darkness87** [darkness87/AMIWeb#9]
![image.png](https://images.zenhubusercontent.com/5d78977a59191331a1b51cd0/3753577a-9d85-4f5f-8be6-0658a00ed125)

**Comment by darkness87** [comment]
기능 구현 일정 어려움으로 기능을 일시적으로 막습니다.

**Comment by endless87** [comment]
구현 가능한 API 개발

**Comment by darkness87** [comment]
#50 티켓으로 작업 진행하였습니다.
